# context version
VERSION ?= 6.6.1
RELEASE ?= 1

# log
VERBOSE            ?= 1
PACKER_LOG         ?= 1
LIBGUESTFS_DEBUG   ?= 1
LIBGUESTFS_TRACE   ?= 0
LIBGUESTFS_MEMSIZE ?= 3072
TTY                ?= $(shell tty)

# default directories
DIR_BUILD     ?= build
DIR_BASE      ?= $(DIR_BUILD)/01_base
DIR_INSTALL   ?= $(DIR_BUILD)/02_installer
DIR_EXPORT    ?= $(DIR_BUILD)/03_export
DIR_PACKER    ?= $(DIR_BUILD)/_packer

# create them if not present
$(shell \
	mkdir -p ${DIR_BASE} \
	mkdir -p ${DIR_INSTALL} \
	mkdir -p ${DIR_EXPORT} \
)

# # don't delete downloaded or installed images
.SECONDARY: $(patsubst %, $(DIR_BASE)/%, $(DISTROS))
.SECONDARY: $(patsubst %, $(DIR_INSTALL)/%.qcow2, $(DISTROS))

.PHONY: context-linux download installer customize help

# this needs to match context-linux/generate-all.sh products
LINUX_CONTEXT_PACKAGES := one-context_${VERSION}-${RELEASE}.deb \
	one-context-${VERSION}-${RELEASE}.el6.noarch.rpm \
	one-context-${VERSION}-${RELEASE}.el7.noarch.rpm \
	one-context-${VERSION}-${RELEASE}.el8.noarch.rpm \
	one-context-${VERSION}-${RELEASE}.el9.noarch.rpm \
	one-context-${VERSION}-${RELEASE}.suse.noarch.rpm \
	one-context-${VERSION}_${RELEASE}.txz \
	one-context-${VERSION}-alt${RELEASE}.noarch.rpm \
	one-context-${VERSION}-r${RELEASE}.apk \
	one-context-linux-${VERSION}-${RELEASE}.iso

LINUX_CONTEXT_PACKAGES_FULL := $(patsubst %, context-linux/out/%, $(LINUX_CONTEXT_PACKAGES))


# discover some binaries
QEMU_BINARY ?= $(shell \
    for _qb in /usr/bin/qemu-system-x86_64 \
	           /usr/libexec/qemu-kvm  \
			   /usr/bin/qemu-kvm; do  \
    \
        if [ -e "$$_qb" ]; then \
			echo $$_qb && exit; \
		fi; \
	done )

# logging func
INFO=sh -c 'if [ $(VERBOSE) = 1 ]; then  echo [INFO] $$1; fi' INFO

# export all variables
export

